books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name="books"

urlpatterns = [
  path("", BooksView.as_view(), name="books"),
  path("<int:pk>", BookDetail.as_view(), name="book"),
  path("<int:pk>/update", UpdateBook.as_view(), name="update"),
  path("create", CreateBook.as_view(), name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

favs/urls.py
from django.urls import path
from favs.views import resolve_add

app_name="favs"

urlpatterns = [
  path("toggle/<int:pk>", resolve_add, name="add"),
]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, CreateMovie, UpdateMovie

app_name = "movies"

urlpatterns = [
    path("", MoviesView.as_view(), name="movies"),
    path("<int:pk>", MovieDetail.as_view(), name="movie"),
    path("<int:pk>/update", UpdateMovie.as_view(), name="update"),
    path("create", CreateMovie.as_view(), name="create"),
]

people/urls.py
from django.urls import path
from people.views import PeopleView, PersonDetail, CreatePerson, UpdatePerson

app_name="people"

urlpatterns = [
  path("", PeopleView.as_view(), name="people"),
  path("<int:pk>", PersonDetail.as_view(), name="person"),
  path("<int:pk>/update", UpdatePerson.as_view(), name="update"),
  path("create", CreatePerson.as_view(), name="create"),
]

books/models.py
from django.urls import reverse
from django.db import models
from core.models import CoreModel


class Book(CoreModel):

  """ Book Model """

  title = models.CharField(max_length=120)
  year = models.IntegerField()
  cover_image = models.ImageField(null=True, blank=True)
  rating = models.FloatField()
  category = models.ForeignKey(
      "categories.Category", on_delete=models.CASCADE, related_name="books")
  writer = models.ForeignKey(
        "people.Person", on_delete=models.CASCADE, related_name="books")

  def __str__(self):
      return self.title

  def get_absolute_url(self):
    return reverse("books:book", kwargs={"pk": self.pk})

  class Meta:
    ordering = ["-created_at"]

people/models.py
from django.urls import reverse
from django.db import models
from core.models import CoreModel

class Person(CoreModel):

  """ Person Model """

  KIND_ACTOR = "actor"
  KIND_DIRECTOR = "director"
  KIND_WRITER = "writer"

  KIND_CHOICES = (
    (KIND_ACTOR, "Actor"),
    (KIND_DIRECTOR, "Director"),
    (KIND_WRITER, "Writer")
  )

  name = models.CharField(max_length=120)
  photo = models.ImageField(null=True, blank=True)
  kind = models.CharField(max_length=15, choices=KIND_CHOICES)

  def __str__(self):
    return self.name
  
  class Meta:
    verbose_name_plural = "People"
    ordering = ["created_at"]

  def get_absolute_url(self):
    return reverse("people:person", kwargs={"pk": self.pk})

books/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from books.models import Book
from reviews import forms as review_forms
from reviews.models import Review

class BooksView(ListView):
  
  model = Book
  paginate_by = 15
  paginate_orphans = 5
  ordering = "-created_at"
  context_object_name = "books"

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['page_title'] = "All Books"
    return context


class BookDetail(DetailView):
  # model = Book
  # context_object_name = 'book'
  def get(self, *args, **kwargs):
    pk = kwargs.get("pk")
    book = Book.objects.get(pk=pk)
    form = review_forms.CreateReviewForm()
    reviews = Review.objects.filter(book=pk)
    return render(
      self.request,
      "books/book_detail.html",
      {'book':book, 'form':form, 'reviews':reviews}
    )


class CreateBook(CreateView):
  model = Book
  fields = (
    "title",
    "year",
    "cover_image",
    "rating",
    "category",
    "writer",
  )


class UpdateBook(UpdateView):
  model = Book
  fields = (
    "title",
    "year",
    "cover_image",
    "rating",
    "category",
    "writer",
  )

people/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from people.models import Person


class PeopleView(ListView):
  
  model = Person
  paginate_by = 15
  paginate_orphans = 5
  ordering = "-created_at"
  context_object_name = "people"
  template_name = "people/people_list.html"

  def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "All People"
        return context


class PersonDetail(DetailView):
  model = Person
  template_name = "people/person_detail.html"
  context_object_name = 'person'


class CreatePerson(CreateView):
  model = Person
  fields = (
    "name",
    "photo",
    "kind",  
  )

class UpdatePerson(UpdateView):
  model = Person
  fields = (
    "name",
    "photo",
    "kind"
  )

templates/mixins/book.html
<div class="h-48 rounded shadow-lg p-2">
  <h3 class="text-gray-900 text-base mb-2"><a href="{% url 'books:book' book.pk %}">{{book.title}}</a></h3>
  <h5 class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{{book.year}}</h5>
</div>

templates/mixins/fav_button.html
{% load on_favs %}
{% on_favs obj as on_favs_boolean %}

<a class="ml-5 bg-blue-400 hover:bg-blue-600 text-white font-bold mt-4 py-2 px-4 rounded" href="{% url 'favs:add' obj.pk %}?kind={{kind}}">
{% if on_favs_boolean %}
  
    Remove from favs!
  
{% else %}
  
      Add to favs!
  
{% endif %}
  </a>

templates/mixins/form.html
<div class="flex justify-center mt-8">
<form method="POST" enctype="multipart/form-data" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    
    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <span>{{error}}</span> 
        {% endfor %}
    {% endif %}

    {% for field in form %}
      <div class="mb-5">
          <label class="block text-gray-700 text-sm font-bold mb-2" for="{{field.auto_id}}">{{field.label}}</label>
          <div class="shadow appearance-none border rounded w-full  text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
          {{field}}
          </div>
      </div>
    {% endfor %}
    
    <button class="bg-blue-400 hover:bg-blue-600 text-white font-bold mt-2 py-2 px-4 rounded w-full">{{cta}}</button>
</form>
</div>

templates/mixins/movie.html
<div class="h-48 rounded shadow-lg p-2">
  <h3 class="text-gray-900 text-base mb-2"><a href="{% url 'movies:movie' movie.pk %}">{{movie.title}}</a></h3>
  <h5 class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{{movie.year}}</h5>
</div>

templates/mixins/person.html
<div class="h-48 rounded shadow-lg p-2">
    <h3 class="text-gray-900 text-base mb-2"><a href="{% url 'people:person' person.pk %}">{{person.name}}</a></h3>
    <h5 class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{{person.kind}}</h5>
  </div>

templates/mixins/review_button.html
{% load on_reviews %}
{% on_reviews obj as on_reviews_boolean %}

{% if on_reviews_boolean %}
  <form class="flex flex-col justify-center align-center p-4 rounded-lg" action="{% url "reviews:add" obj.pk %}?kind={{kind}}" method="POST">
    {% csrf_token %}
    <button class="ml-5 bg-blue-400 hover:bg-blue-600 text-white font-bold my-4 py-2 px-4 rounded">
      Delete my Review
    </button>
  </form>
  

{% else %}
  <form class=" flex flex-col justify-center align-center border-2 p-4 rounded-lg" action="{% url "reviews:add" obj.pk %}?kind={{kind}}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button class="w-2/5 ml-5 bg-blue-400 hover:bg-blue-600 text-white font-bold mt-4 py-2 px-4 rounded" >
      Save
    </button>
  </form>
  
{% endif %}