books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name="books"

urlpatterns = [
  path("", BooksView.as_view(), name="books"),
  path("<int:pk>", BookDetail.as_view(), name="book"),
  path("<int:pk>/update", UpdateBook.as_view(), name="update"),
  path("create", CreateBook.as_view(), name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

books/models.py
from django.urls import reverse
from django.db import models
from core.models import CoreModel


class Book(CoreModel):

  """ Book Model """

  title = models.CharField(max_length=120)
  year = models.IntegerField()
  cover_image = models.ImageField(null=True, blank=True)
  rating = models.FloatField()
  category = models.ForeignKey(
      "categories.Category", on_delete=models.CASCADE, related_name="books")
  writer = models.ForeignKey(
        "people.Person", on_delete=models.CASCADE, related_name="books")

  def __str__(self):
      return self.title

  def get_absolute_url(self):
    return reverse("books:book", kwargs={"pk": self.pk})

  class Meta:
    ordering = ["-created_at"]

books/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from books.models import Book
from reviews import forms as review_forms
from reviews.models import Review

class BooksView(ListView):
  
  model = Book
  paginate_by = 15
  paginate_orphans = 5
  ordering = "-created_at"
  context_object_name = "books"

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['page_title'] = "All Books"
    return context


class BookDetail(DetailView):
  # model = Book
  # context_object_name = 'book'
  def get(self, *args, **kwargs):
    pk = kwargs.get("pk")
    book = Book.objects.get(pk=pk)
    form = review_forms.CreateReviewForm()
    reviews = Review.objects.filter(book=pk)
    return render(
      self.request,
      "books/book_detail.html",
      {'book':book, 'form':form, 'reviews':reviews}
    )


class CreateBook(CreateView):
  model = Book
  fields = (
    "title",
    "year",
    "cover_image",
    "rating",
    "category",
    "writer",
  )


class UpdateBook(UpdateView):
  model = Book
  fields = (
    "title",
    "year",
    "cover_image",
    "rating",
    "category",
    "writer",
  )

templates/books/book_detail.html
{% extends "base.html" %}

{% block page_title %}
  {{book.title}}
{% endblock page_title %}


{% block content %}

<div class="flex flex-col items-center bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
<h2 class="font-bold">{{book.title}}</h2>
<div class="flex items-center my-2">
  <div class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700">{{book.year}}</div>
  <div class="bg-orange-400 text-white px-3 shadow-md py-1 rounded-full mx-4">{{book.category}}</div>
  <div class="text-red-600">♥︎{{book.rating}}</div>
</div>
<div class="my-2">Writer:
  <div class="inline-block bg-white shadow-md rounded-full px-3 py-1 text-sm font-semibold text-gray-700">{{book.writer}}</div>
</div>
<div class="mb-8">
  <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold mt-4 py-2 px-4 rounded" href="{% url 'books:update' book.pk %}">Edit Book</a>
  {% if user.is_authenticated %}
    {% include "mixins/fav_button.html" with obj=book kind='book' %}
  {% endif %}
</div>

<div class="flex flex-col justify-center">
  {% if user.is_authenticated %}
    {% include "mixins/review_button.html" with obj=book kind='book' %}
  {% endif %}
  {% for review in reviews %}
    <div class="flex jstify-between">
      <div class="border rounded-full">
        {{review.created_by}}
      </div>
      <div>{{review}}</div>
    </div>
  {% endfor %}
  </div>
</div>

{% endblock content %}

templates/books/book_form.html
{% extends "base.html" %}

{% block page_title %}
  Modify Book
{% endblock page_title %}

{% block content %}

  {% include 'mixins/form.html' with form=form cta="Save" %}

{% endblock content %}

templates/books/book_list.html
{% extends "base.html" %}

{% block page_title %}
  Books
{% endblock page_title %}

{% block content %}
<div class="px-5">
  <h2 class="ml-1 text-3xl text-blue-600">Books</h2>
  <div class="grid my-5 grid-cols-4 gap-10">
	{% for book in books %}
    {% include "mixins/book.html" with book=book %}
	{% endfor %}
  </div>
<hr />
</div>
<div class="mt-2 flex justify-center">
  <div>
  {% if page_obj.has_previous %}
        <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold py-1 px-2 rounded" href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}

    <span class="font-bold text-blue-600">
    Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
    </span>

    {% if page_obj.has_next  %}
        <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold py-1 px-2 rounded" href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}
  </div>
</div>
{% endblock content %}