books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name="books"

urlpatterns = [
  path("", BooksView.as_view(), name="books"),
  path("<int:pk>", BookDetail.as_view(), name="book"),
  path("<int:pk>/update", UpdateBook.as_view(), name="update"),
  path("create", CreateBook.as_view(), name="create"),
]

categories/urls.py
from django.urls import path
from categories.views import CategoryDetail

app_name="categories"

urlpatterns = [
  path("<int:pk>", CategoryDetail.as_view(), name="category"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("categories/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("users/", include("users.urls", namespace="users")),
    path("favs/", include("favs.urls", namespace="favs")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, CreateMovie, UpdateMovie

app_name = "movies"

urlpatterns = [
    path("", MoviesView.as_view(), name="movies"),
    path("<int:pk>", MovieDetail.as_view(), name="movie"),
    path("<int:pk>/update", UpdateMovie.as_view(), name="update"),
    path("create", CreateMovie.as_view(), name="create"),
]

users/urls.py
from django.urls import path
from users.views import logout_view, LoginView, SignUpView, UserProfileView, UpdateProfileView, UpdatePasswordView

app_name = "people"

urlpatterns = [
    path("logout", logout_view, name="logout"),
    path("login", LoginView.as_view(), name="login"),
    path("signup", SignUpView.as_view(), name="signup"),
    path("<int:pk>", UserProfileView.as_view(), name="profile"),
    path("update-profile/", UpdateProfileView.as_view(), name="update"),
    path("update-passwod/", UpdatePasswordView.as_view(), name="password"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
	<style>
		input, select {
			width: 100%;
			padding-left: 0.75rem;
			padding-right: 0.75rem;
			padding-top: 0.5rem;
			padding-bottom: 0.5rem;
    }
	</style>
	<title>{% block page_title %}{% endblock page_title %} | Nomad Media</title>
</head>

<body>
	{% include 'partials/header.html' %} {% block content %} {% endblock content %} {% include 'partials/footer.html' %}
</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block page_title %}
  Home
{% endblock page_title %}

{% block content %}
<div class="my-8 px-5">
  <div class="flex items-center">
	<h2 class="text-3xl text-blue-600">Movies</h2> 
  <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold ml-2 py-2 px-4 rounded" href="{% url 'movies:create' %}">create</a>
  </div>
  <div class="grid mt-5 grid-cols-4 gap-10">
	{% for movie in movies %}
    {% include "mixins/movie.html" with movie=movie %}
	{% endfor %}
  <div class=" rounded shadow-lg p-2">
	<a class="text-blue-400" href="{% url 'movies:movies' %}">See all movies &rarr;</a>
  </div>
  </div>
</div>
	<hr />

<div class="my-8 px-5">
  <div class="flex items-center">
  <h2 class="text-3xl text-blue-600">Books</h2>
  <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold ml-2 py-2 px-4 rounded" href="{% url 'books:create' %}">create</a>
  </div>
  <div class="grid mt-5 grid-cols-4 gap-10">
	{% for book in books %}
    {% include "mixins/book.html" with book=book %}
	{% endfor %}
  <div class=" rounded shadow-lg p-2">
	<a class="text-blue-400" href="{% url 'books:books' %}">See all books &rarr;</a>
  </div>
  </div>
</div>
	<hr />

<div class="my-8 px-5">
  <div class="flex items-center">
	<h2 class="text-3xl text-blue-600">People</h2> 
  <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold ml-2 py-2 px-4 rounded" href="{% url 'people:create' %}">create</a>
  </div>
  <div class="grid grid-cols-4 gap-10">
	{% for person in people %}
	  {% include "mixins/person.html" with person=person %}
	{% endfor %}
  <div class=" rounded shadow-lg p-2">
	<a class="text-blue-400" href="{% url 'people:people' %}">See all people &rarr;</a>
  </div>
  </div>
</div>
	<hr />
{% endblock content %}

templates/search.html
{% extends "base.html" %}

{% block page_title %}
  Search
{% endblock page_title %}


{% block content %}

<div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">

<form class="flex mb-2" method="GET"> 
  <input name="term" class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="text" placeholder="Search Movie, Book or Person" />
  <button class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white ml-2 py-2 px-4 border border-blue-500 hover:border-transparent rounded">Search</button>
</form>


<h3 class="block text-gray-700 text-center text-sm font-bold mb-5 mt-10">
  {% if term %}
    Searching by: {{term}}
  {% else %}
    Categories
  {% endif %}
</h3>
{% if not term %}
  <div class="inline-block relative w-full flex flex-wrap">
    {% for category in categories %}
      <div class="bg-orange-400 text-white px-5 shadow-md py-2 rounded-full mb-2 mr-2">
        <a href="{% url 'categories:category' category.pk %}">{{category.name}}</a>
      </div>
    {% endfor %}
  </div>
{% endif %}
<hr />
{% if term %}
<div class="mt-10">
    <h3 class="block text-gray-700 text-lg font-bold mb-10 mt-10">
      {% if not movies %}
        No Movies Found
      {% else %}
        Movies:
      {% endif %}
    </h3>
    <div class="grid my-5 grid-cols-4 gap-10">
      {% for movie in movies %}
        {% include "mixins/movie.html" with movie=movie %}
      {% endfor %}
      </div>
    <hr />
</div>
<div class="mt-10">
    <h3 class="block text-gray-700 text-lg font-bold mb-10 mt-10">
      {% if not books %}
        No Books Found
      {% else %}
        Books
      {% endif %}
    </h3>
    <div class="grid my-5 grid-cols-4 gap-10">
    {% for book in books %}
      {% include "mixins/book.html" with book=book %}
    {% endfor %}
    </div>
    <hr />
</div>
<div class="mt-10">
    <h3 class="block text-gray-700 text-lg font-bold mb-10 mt-10">
      {% if not people %}
        No People Found
      {% else %}
        People
      {% endif %}
    </h3>
    <hr />
     <div class="grid my-5 grid-cols-4 gap-10">
      {% for person in people %}
        {% include "mixins/person.html" with person=person %}
      {% endfor %}
      </div>
</div>
{% endif %}
</div>

{% endblock content %}